### ISSUE TITLE
Error: There is no extension able to load the configuration for "clooder_imagine" (in..

### ISSUE THREAD

**Issue by San2k** [flug/imagine-bundle#2]
Hi.
Tried to install, but got this:

FileLoaderLoadException in FileLoader.php line 125:
There is no extension able to load the configuration for "clooder_imagine" (in /Users/sandropuljic/Documents/devel/www/mobile/app/config/config.yml). Looked for namespace "clooder_imagine", found "framework", "security", "twig", "monolog", "swiftmailer", "assetic", "doctrine", "sensio_framework_extra", "tb_mobile", "guzzle", "jms_serializer", "bbit_async_dispatcher", "tbbc_cache", "hwi_oauth", "liip_imagine", "acme_demo", "web_profiler", "sensio_distribution" in /Users/sandropuljic/Documents/devel/www/mobile/app/config/config.yml (which is being imported from "/Users/sandropuljic/Documents/devel/www/mobile/app/config/config_dev.yml").

**Comment by flug** [comment]
you added in the AppKernel? 
```php
new Clooder\ImagineBundle\ClooderImagineBundle() ? 
```

**Comment by San2k** [comment]
No. But after i did, here is a new problem:
Could not find data loader "clooder_loader" for "menu_thumb" filter type
500 Internal Server Error - InvalidArgumentException

my config:

``` yaml
liip_imagine:
    data_loader:  clooder_loader
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        menu_thumb:
            quality: 75
            filters:
                thumbnail: { size: [88, 67], mode: outbound }

clooder_imagine:
    cache_directory: %kernel.root_dir%/../web/uploads
```
