### ISSUE TITLE
Tag a new release version

### ISSUE THREAD

**Issue by migmolrod** [flug/imagine-bundle#3]
What about tagging a new release version, so we, users with "minimum-stability" in our composer.json, are able to actually use the new version (which seems cleaner, more like a 'plugin' for LiipImagineBundle, unlike your first versions which seem a full fork)?

After spending literally hours and hours diving into the scarce and incomplete instructions for Streams in original LiipImagineBundle documentation, I'd like to give this a try but without the need to 'override' the LiipImagineBundle and without the need to change my minimum stability.

**Comment by flug** [comment]
I have not tried with the new version of 'LiipImagineBundle'. My bundle in versions 1 is an adapter which complements LiipImagineBundle in order to dynamically download images via the web.
Feel free to contribute with a new version :D .

**Comment by migmolrod** [comment]
Ah ok. So we're supposed to use the **v1.x versions**, right?

I was trying to follow instructions in master. And what I see right now is that master does not work out of the box (it's trying to use inexistent classes, from previous versions of our bundle I guess). For example, in Resources/config/services.yml we see:

``` yaml
parameters:
    clooder.imagine.twig.class: Clooder\ImagineBundle\Twig\TwigImagineExtension
    clooder.engine.filter.class: Clooder\ImagineBundle\Engine\FilterImagine
    clooder.imagine.factory.class: Clooder\ImagineBundle\Factory\ImagineFactory
    clooder.imagine.manager.class: Clooder\ImagineBundle\Manager\ImagineManager

    clooder.filter.configuration.class: Clooder\ImagineBundle\Configuration\FilterConfiguration
    clooder.imagine.routing.loader.class: Clooder\ImagineBundle\Routing\ClooderLoader
    clooder.imagine.controller.action: Clooder\ImagineBundle\Controller\ImagineController
```

All these classes does not even exist in master branch. But they do in v1.x tags and below.

And about the documentation of **master** branch, the very first step:

``` sh
composer require clooder/imagine-bundle : 2.*@dev
```

is not even working, since there are no v.2.x tags. I've realized that it doesn't matter if my minimum-stability is set as dev (I tried it in a new branch in my project to not mess up things XD). That command simply fails.
