### ISSUE TITLE
how to use it with a CDN ?

### ISSUE THREAD

**Issue by ibasaw** [flug/imagine-bundle#4]
hi,

here my config:

```
clooder_imagine:
    cache_directory: %assetic_write_to%media/cache

liip_imagine:
    data_loader: clooder_loader
    loaders:
        default:
            filesystem:
                data_root: %assetic_write_to%media/image
    filter_sets:
        sylius_small:
            filters:
                thumbnail: { size: [68, 102], mode: inset }
        sylius_medium:
            data_loader: clooder_loader
            filters:
                thumbnail: { size: [255, 382], mode: inset }
```

and here the call in the twig template:

cdn_media is an absolute path like this: http://cdn.xxx.com/media/image

```
{{ cdn_media~image.path|imagine_filter('sylius_medium') }}
```

but the path is not correct:

```
http://cdn.xxx.com/media/imagehttp://dev.xxx.com/app_dev.php/media/cache/resolve/sylius_medium/27/b8/89f5b478cf085a6583b2bc0ae06a.jpeg
```

whats wrong here ?
